name: Deploy to Firebase Hosting on push to main

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}'
          channelId: live
          projectId: exalted-splicer-456312-e8 # <<< SEU ID DE PROJETO CORRETO
          # Adicionando o comando explícito com --project
          args: deploy --only hosting --project exalted-splicer-456312-e8 